#!/bin/bash

# No need to verify updates to these refs
ignore_refs=("HEAD" "ORIG_HEAD")

if [ "$1" == "prepared" ]; then
  ref_update=""

  # Read updates from standard input
  while read oldref newref refname; do
   if ! [[ "${ignore_refs[@]}" =~ "$refname" ]]; then
    ref_update="$oldref $newref $refname"
   fi
  done

  if ! [ "$ref_update" == "" ]; then
    bark verify -r $ref_update
    exit_status=$(echo $?)
    if [ $exit_status -ne 0 ]; then
      exit 1
    fi
  fi

fi


